#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
#define HAL_ADC0_ENABLE                  (1)

#define BSP_ADC0_NEG_INPUT               (_ADC_SINGLECTRL_NEGSEL_VSS)
// [ADC0]$

// $[BTL_BUTTON]
#define HAL_BTL_BUTTON_ENABLE            (1)

// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CAN0]
// [CAN0]$

// $[CMU]
// [CMU]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IOEXP]
// [IOEXP]$

// $[LCD]
// [LCD]$

#define BSP_LED0_PORT    gpioPortE
#define BSP_LED0_PIN     12
#define BSP_LED1_PORT    gpioPortE
#define BSP_LED1_PIN     11

// $[LED]
#define BSP_LED_PRESENT                  (1)

#define BSP_LED_COUNT                    (2U)
#define BSP_LED_INIT                     { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN } }
#define BSP_LED_POLARITY                 (1)
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
#define PORTIO_TIMER1_CC0_PIN            (13U)
#define PORTIO_TIMER1_CC0_PORT           (gpioPortC)
#define PORTIO_TIMER1_CC0_LOC            (0U)

// [TIMER1]$

// $[UART0]
// [UART0]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_RX_PIN             (8U)
#define PORTIO_USART0_RX_PORT            (gpioPortB)
#define PORTIO_USART0_RX_LOC             (4U)

#define PORTIO_USART0_TX_PIN             (7U)
#define PORTIO_USART0_TX_PORT            (gpioPortB)
#define PORTIO_USART0_TX_LOC             (4U)

#define HAL_USART0_ENABLE                (1)

#define BSP_USART0_TX_PIN                (7U)
#define BSP_USART0_TX_PORT               (gpioPortB)
#define BSP_USART0_TX_LOC                (4U)

#define BSP_USART0_RX_PIN                (8U)
#define BSP_USART0_RX_PORT               (gpioPortB)
#define BSP_USART0_RX_LOC                (4U)

#define HAL_USART0_BAUD_RATE             (9600UL)
#define HAL_USART0_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_RX_PIN             (1U)
#define PORTIO_USART1_RX_PORT            (gpioPortC)
#define PORTIO_USART1_RX_LOC             (0U)

#define PORTIO_USART1_TX_PIN             (0U)
#define PORTIO_USART1_TX_PORT            (gpioPortC)
#define PORTIO_USART1_TX_LOC             (0U)

#define HAL_USART1_ENABLE                (1)

#define BSP_USART1_TX_PIN                (0U)
#define BSP_USART1_TX_PORT               (gpioPortC)
#define BSP_USART1_TX_LOC                (0U)

#define BSP_USART1_RX_PIN                (1U)
#define BSP_USART1_RX_PORT               (gpioPortC)
#define BSP_USART1_RX_LOC                (0U)

#define HAL_USART1_BAUD_RATE             (9600UL)
#define HAL_USART1_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [USART1]$

// $[USART2]
// [USART2]$

// $[USART3]
// [USART3]$

// $[VCOM]
#define HAL_VCOM_ENABLE                  (1)

// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

